
import { TranslationDictionary, SupportedLanguage } from './types';


// Using a high-quality medical icon from a CDN to ensure it loads in all environments
export const LOGO_URL = "https://raw.githubusercontent.com/StnkRB/dawai/main/logo-india-flag8.jpg"

export const LANGUAGES: { code: SupportedLanguage; label: string; nativeLabel: string }[] = [
  { code: 'en', label: 'English', nativeLabel: 'English' },
  // Indian Languages
  { code: 'hi', label: 'Hindi', nativeLabel: 'हिंदी' },
  { code: 'bn', label: 'Bengali', nativeLabel: 'বাংলা' },
  { code: 'te', label: 'Telugu', nativeLabel: 'తెలుగు' },
  { code: 'ta', label: 'Tamil', nativeLabel: 'தமிழ்' },
  { code: 'mr', label: 'Marathi', nativeLabel: 'मराठी' },
  { code: 'gu', label: 'Gujarati', nativeLabel: 'ગુજરાતી' },
  { code: 'kn', label: 'Kannada', nativeLabel: 'ಕನ್ನಡ' },
  { code: 'ml', label: 'Malayalam', nativeLabel: 'മലയാളം' },
  { code: 'pa', label: 'Punjabi', nativeLabel: 'ਪੰਜਾਬੀ' },
  { code: 'or', label: 'Odia', nativeLabel: 'ଓଡ଼ିଆ' },
  { code: 'as', label: 'Assamese', nativeLabel: 'অসমীয়া' },
  { code: 'ur', label: 'Urdu', nativeLabel: 'اردو' },
  { code: 'sa', label: 'Sanskrit', nativeLabel: 'संस्कृतम्' },
  { code: 'ne', label: 'Nepali', nativeLabel: 'नेपाली' },
  { code: 'ks', label: 'Kashmiri', nativeLabel: 'کشمیر' },
  { code: 'sd', label: 'Sindhi', nativeLabel: 'सिंधी' },
  { code: 'kok', label: 'Konkani', nativeLabel: 'कोंकणी' },
  { code: 'mai', label: 'Maithili', nativeLabel: 'मैथिली' },
  { code: 'doi', label: 'Dogri', nativeLabel: 'डोगरी' },
  // New: Arabic & African Languages
  { code: 'ar', label: 'Arabic', nativeLabel: 'العربية' },
  { code: 'sw', label: 'Swahili', nativeLabel: 'Kiswahili' },
  { code: 'am', label: 'Amharic', nativeLabel: 'አማርኛ' },
  { code: 'ha', label: 'Hausa', nativeLabel: 'Harshen Hausa' },
  { code: 'yo', label: 'Yoruba', nativeLabel: 'Yorùbá' },
  { code: 'zu', label: 'Zulu', nativeLabel: 'isiZulu' },
  { code: 'so', label: 'Somali', nativeLabel: 'Soomaaliga' },
];

const EN_TRANSLATIONS = {
    welcome: 'Welcome',
    scanNew: 'Read Doctor Prescription',
    scanReport: 'Scan Report',
    explainReport: 'Explain Report',
    history: 'Past Records',
    settings: 'Change Language',
    processing: 'Analyzing document...',
    analyzingReport: 'Analyzing...',
    save: 'Save Record',
    delete: 'Delete',
    recordVoice: 'Add Voice Note',
    stopRecording: 'Stop Recording',
    playVoice: 'Play Note',
    playExplanation: 'Listen to Explanation',
    stopExplanation: 'Stop Audio',
    generateVisual: 'Show Anatomy Diagram',
    visualReady: 'Visual Aid Generated',
    doctor: 'Doctor',
    patient: 'Patient',
    phone: 'Phone',
    medications: 'Medicines',
    summary: 'Summary',
    condition: 'Diagnosis',
    anatomy: 'Affected Body Part',
    nextSteps: 'What to do next',
    searchPlaceholder: 'Search Doctor, Patient or Diagnosis...',
    noHistory: 'No records found.',
    back: 'Go Back',
    languageName: 'English',
    takePhoto: 'Take Photo',
    uploadPhoto: 'Upload Image',
    deleteConfirm: 'Are you sure?',
    listening: 'Recording...',
    recordingSaved: 'Voice note saved',
    medicinePurpose: 'Uses',
    setAlarm: 'Set Reminder',
    alarmSet: 'Reminder Set',
    instructions: 'Instructions',
    generalInstructions: 'Diet & Suggestions',
    open: 'Open',
    stopAlarm: 'Stop Alarm',
    readsHandwritten: 'Reads Handwritten & Typed Notes',
    pleaseWait: 'Please wait...',
    simpleExplanation: 'Simple Explanation',
    transcribing: 'Understanding audio...',
    transcript: 'Voice Note Transcript',
    viewImage: 'See Photo',
    healthAdvice: 'Health Advice from Doctor',
    generatingAudio: 'Creating Audio...',
    savedSuccess: '✓ Saved',
    todoList: 'Doctor Advice',
    dailyTimetable: 'Daily Schedule',
    noEvents: 'No reminders set. Add reminders to your medicines to see them here.',
    addToSchedule: 'Add to Schedule',
    removeFromSchedule: 'Remove',
    autoScheduled: 'Auto-Scheduled',
    clearAll: 'Clear All',
    clearAllConfirm: 'This will delete ALL your records. Are you sure?',
};

const createTranslation = (overrides: Partial<typeof EN_TRANSLATIONS>): typeof EN_TRANSLATIONS => {
  return { ...EN_TRANSLATIONS, ...overrides };
};

export const TRANSLATIONS: TranslationDictionary = {
  en: EN_TRANSLATIONS,
  hi: createTranslation({
    scanNew: 'डॉक्टर की पर्ची पढ़ें',
    history: 'पुराने रिकॉर्ड',
    settings: 'भाषा बदलें',
    processing: 'जाँच हो रही है...',
    condition: 'बीमारी',
    summary: 'सरल विवरण',
    playExplanation: 'विवরণ सुनें',
    stopExplanation: 'आवाज़ रोकें',
    generateVisual: 'चित्र देखें',
    medications: 'दवाइयाँ',
    generalInstructions: 'परहेज और सलाह',
    save: 'सहेजें',
    delete: 'हटाएं',
    doctor: 'डॉक्टर',
    patient: 'मरीज',
    phone: 'फ़ोन',
    medicinePurpose: 'उपयोग',
    setAlarm: 'रिमाइंडर',
    recordVoice: 'आवाज़ रिकॉर्ड करें',
    searchPlaceholder: 'खोजें...',
    noHistory: 'कोई रिकॉर्ड नहीं मिला',
    stopAlarm: 'अलार्म बंद करें',
    visualReady: 'चित्र तैयार है',
    languageName: 'Hindi',
    readsHandwritten: 'हाथ की लिखाई और टाइप पर्चे पढ़ता है',
    anatomy: 'शरीर का अंग',
    pleaseWait: 'कृपया प्रतीक्षा करें...',
    simpleExplanation: 'सरल विवरण',
    transcribing: 'आवाज़ समझ रहा हूँ...',
    transcript: 'आवाज़ का अनुवाद',
    viewImage: 'फोटो देखें',
    healthAdvice: 'डॉक्टर की स्वास्थ्य सलाह',
    generatingAudio: 'आवाज़ बना रहा है...',
    savedSuccess: '✓ सहेजा गया',
    todoList: 'डॉक्टर की सलाह',
    dailyTimetable: 'दैनिक समय सारिणी',
    noEvents: 'कोई रिमाइंडर सेट नहीं है। यहाँ देखने के लिए अपनी दवाओं में रिमाइंडर जोड़ें।',
    addToSchedule: 'शेड्यूल में जोड़ें',
    removeFromSchedule: 'हटाएं',
    autoScheduled: 'स्वत: समय निर्धारित',
    clearAll: 'सब मिटाएं',
    clearAllConfirm: 'इससे आपके सभी रिकॉर्ड मिटा दिए जाएंगे। क्या आप सुनिश्चित हैं?',
  }),
  bn: createTranslation({
    scanNew: 'ডাক্তারের প্রেসক্রিপশন পড়ুন',
    history: 'পুরানো রেকর্ড',
    settings: 'ভাষা পরিবর্তন',
    processing: 'বিশ্লেষণ করা হচ্ছে...',
    condition: 'রোগ নির্ণয়',
    summary: 'সারাংশ',
    playExplanation: 'ব্যাখ্যা শুনুন',
    stopExplanation: 'অডিও বন্ধ',
    generateVisual: 'চিত্র দেখুন',
    medications: 'ওষুধ',
    generalInstructions: 'পরামর্শ',
    save: 'সংরক্ষণ',
    delete: 'মুছুন',
    doctor: 'ডাক্তার',
    patient: 'রোগী',
    phone: 'ফোন',
    medicinePurpose: 'ব্যবহার',
    setAlarm: 'রিমাইন্ডার',
    recordVoice: 'ভয়েস নোট',
    searchPlaceholder: 'অনুসন্ধান...',
    noHistory: 'কোন রেকর্ড পাওয়া যায়নি',
    stopAlarm: 'অ্যালার্ম বন্ধ',
    languageName: 'Bengali',
    readsHandwritten: 'হাতে লেখা এবং টাইপ করা নোট পড়ে',
    anatomy: 'আক্রান্ত অঙ্গ',
    pleaseWait: 'দয়া করে অপেক্ষা করুন...',
    simpleExplanation: 'সহজ ব্যাখ্যা',
    visualReady: 'চিত্র তৈরি হয়েছে',
    transcribing: 'কথা বোঝা হচ্ছে...',
    transcript: 'ভয়েস নোট প্রতিলিপি',
    viewImage: 'ছবি দেখুন',
    healthAdvice: 'ডাক্তারের স্বাস্থ্য পরামর্শ',
    generatingAudio: 'অডিও তৈরি হচ্ছে...',
    savedSuccess: '✓ সংরক্ষিত',
    todoList: 'ডাক্তারের পরামর্শ',
    dailyTimetable: 'দৈনিক সময়সূচী',
    addToSchedule: 'তালিকায় যোগ করুন',
    removeFromSchedule: 'সরান',
    autoScheduled: 'স্বয়ংক্রিয় সময়',
    clearAll: 'সব মুছে ফেলুন',
    clearAllConfirm: 'এটি আপনার সমস্ত রেকর্ড মুছে ফেলবে। আপনি কি নিশ্চিত?',
  }),
  te: createTranslation({
    scanNew: 'డాక్టర్ చీటీ చదవండి',
    history: 'గత రికార్డులు',
    settings: 'భాష మార్చండి',
    processing: 'విశ్లేషిస్తోంది...',
    condition: 'వ్యాధి నిర్ధారణ',
    summary: 'సారాంశం',
    playExplanation: 'వివరణ వినండి',
    stopExplanation: 'ఆపండి',
    generateVisual: 'చిత్రం చూడండి',
    medications: 'మందులు',
    generalInstructions: 'ఆహారం & సూచనలు',
    save: 'భద్రపరచు',
    delete: 'తొలగించు',
    doctor: 'వైద్యుడు',
    patient: 'రోగి',
    phone: 'ఫోన్',
    medicinePurpose: 'ఉపయోగాలు',
    setAlarm: 'రిమైండర్',
    recordVoice: 'వాయిస్ రికార్డ్',
    searchPlaceholder: 'శోధించండి...',
    noHistory: 'రికార్డులు లేవు',
    stopAlarm: 'అలారం ఆపు',
    languageName: 'Telugu',
    readsHandwritten: 'చేతిరాత మరియు టైప్ చేసినవి చదువుతుంది',
    anatomy: 'ప్రభావిత భాగం',
    pleaseWait: 'దయచేసి వేచి ఉండండి...',
    simpleExplanation: 'సాధారణ వివరణ',
    visualReady: 'చిత్రం సిద్ధంగా ఉంది',
    transcribing: 'వాయిస్ అర్థం చేసుకోవడం...',
    transcript: 'వాయిస్ ట్రాన్స్క్రిప్ట్',
    viewImage: 'ఫోటో చూడండి',
    healthAdvice: 'వైద్యుని సలహా',
    generatingAudio: 'ఆడియో సిద్ధమవుతోంది...',
    savedSuccess: '✓ భద్రపరచబడింది',
    todoList: 'వైద్యుని సలహా',
    dailyTimetable: 'రోజువారీ షెడ్యూల్',
    addToSchedule: 'షెడ్యూల్‌కు జోడించు',
    removeFromSchedule: 'తొలగించు',
    autoScheduled: 'స్వయంచాలక సమయం',
    clearAll: 'అన్నీ తొలగించు',
    clearAllConfirm: 'ఇది మీ అన్ని రికార్డులను తొలగిస్తుంది. మీకు ఖచ్చితంగా తెలుసా?',
  }),
  ta: createTranslation({
    scanNew: 'மருத்துவர் சீட்டு படி',
    history: 'வரலாறு',
    settings: 'மொழி மாற்றம்',
    processing: 'ஆய்வு செய்கிறது...',
    condition: 'நோய் கண்டறிதல்',
    summary: 'சுருக்கம்',
    playExplanation: 'விளக்கம் கேள்',
    stopExplanation: 'நிறுத்து',
    generateVisual: 'படம் பார்',
    medications: 'மருந்துகள்',
    generalInstructions: 'உணவு & ஆலோசனைகள்',
    save: 'சேமி',
    delete: 'நீக்கு',
    doctor: 'மருத்துவர்',
    patient: 'நோயாளி',
    phone: 'தொலைபேசி',
    medicinePurpose: 'பயன்கள்',
    setAlarm: 'நினைவூட்டல்',
    recordVoice: 'குரல் பதிவு',
    searchPlaceholder: 'தேடு...',
    noHistory: 'பதிவுகள் இல்லை',
    stopAlarm: 'அலாரத்தை நிறுத்து',
    languageName: 'Tamil',
    readsHandwritten: 'கையெழுத்து மற்றும் டைப் செய்ததை படிக்கும்',
    anatomy: 'பாதிக்கப்பட்ட பகுதி',
    pleaseWait: 'தயவுசெய்து காத்திருங்கள்...',
    simpleExplanation: 'எளிய விளக்கம்',
    visualReady: 'படம் தயாராக உள்ளது',
    transcribing: 'குரலைக் கேட்கிறது...',
    transcript: 'குரல் குறிப்பு',
    viewImage: 'படம் பார்க்க',
    healthAdvice: 'மருத்துவரின் ஆலோசனை',
    generatingAudio: 'ஒலி உருவாகிறது...',
    savedSuccess: '✓ சேமிக்கப்பட்டது',
    todoList: 'மருத்துவர் ஆலோசனை',
    dailyTimetable: 'தினசரி அட்டவணை',
    addToSchedule: 'அட்டவணையில் சேர்',
    removeFromSchedule: 'நீக்கு',
    autoScheduled: 'தானியங்கி நேரம்',
    clearAll: 'அனைத்தையும் அழி',
    clearAllConfirm: 'இது உங்கள் எல்லா பதிவுகளையும் நீக்கிவிடும். நீங்கள் உறுதியாக இருக்கிறீர்களா?',
  }),
  mr: createTranslation({
    scanNew: 'डॉक्टरांची चिट्ठी वाचा',
    history: 'जुने रेकॉर्ड',
    settings: 'भाषा बदला',
    processing: 'तपासत आहे...',
    condition: 'निदान',
    summary: 'सारांश',
    playExplanation: 'स्पष्टीकरण ऐका',
    stopExplanation: 'थांबवा',
    generateVisual: 'चित्र पहा',
    medications: 'औषधे',
    generalInstructions: 'पथ्य आणि सल्ला',
    save: 'जतन करा',
    delete: 'हटवा',
    doctor: 'डॉक्टर',
    patient: 'रुग्ण',
    phone: 'फोन',
    medicinePurpose: 'उपयोग',
    setAlarm: 'रिमाइंडर',
    recordVoice: 'आवाज रेकॉर्ड करा',
    searchPlaceholder: 'शोधा...',
    noHistory: 'कोणतेही रेकॉर्ड नाही',
    stopAlarm: 'अलार्म थांबवा',
    languageName: 'Marathi',
    readsHandwritten: 'हाताने लिहिलेले आणि टाइप केलेले वाचते',
    anatomy: 'शरीराचा भाग',
    pleaseWait: 'कृपया प्रतीक्षा करा...',
    simpleExplanation: 'सोपे स्पष्टीकरण',
    visualReady: 'चित्र तयार आहे',
    transcribing: 'आवाज समजून घेत आहे...',
    transcript: 'आवाजाचा मजकूर',
    viewImage: 'फोटो पहा',
    healthAdvice: 'डॉक्टरांचा सल्ला',
    generatingAudio: 'ऑडिओ तयार होत आहे...',
    savedSuccess: '✓ जतन केले',
    todoList: 'डॉक्टरांचा सल्ला',
    dailyTimetable: 'दैनिक वेळापत्रक',
    addToSchedule: 'वेळापत्रकात जोडा',
    removeFromSchedule: 'काढा',
    autoScheduled: 'स्वयं वेळ',
    clearAll: 'सर्व हटवा',
    clearAllConfirm: 'यामुळे तुमचे सर्व रेکॉर्ड हटवले जातील. आपली खात्री आहे का?',
  }),
};
